# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFood' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppFood

  target 'AppFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
