# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFood' do
    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'Reachability' 
    pod 'CRPageViewController'
    pod 'PullToMakeSoup', '~> 2.0'
    use_frameworks!

  target 'AppFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
